version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: /home/user/inventoryqabot/src/database/dockerfile
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: